name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1'

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

      - name: Deploy Docker container on server
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            docker login cr.yandex -u oauth -p $(echo ${{ secrets.YC_DOCKER_AUTH }}) || true
            docker pull $REGISTRY:release-${{ github.event.inputs.version }}_latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:3000 $REGISTRY:release-${{ github.event.inputs.version }}_latest
          EOF
