name: Fix Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to fix (number)'
        required: true

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  GH_PAT: ${{ secrets.GH_PAT }}
  YC_DOCKER_AUTH: ${{ secrets.YC_DOCKER_AUTH }}

jobs:
  fix-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Make fixes (if needed)
        run: |
          echo "You can add fix commands here if needed"
          # Example: sed -i 's/OldName/NewName/g' src/client/pages/About.tsx

      - run: npm run build

      - name: Login to Yandex Container Registry
        run: echo "$YC_DOCKER_AUTH" | docker login --username oauth --password-stdin cr.yandex

      - name: Build and push fixed Docker image
        run: |
          docker build -t $REGISTRY:release-${{ github.event.inputs.version }}_fix1 .
          docker push $REGISTRY:release-${{ github.event.inputs.version }}_fix1
          docker tag $REGISTRY:release-${{ github.event.inputs.version }}_fix1 $REGISTRY:release-${{ github.event.inputs.version }}_latest
          docker push $REGISTRY:release-${{ github.event.inputs.version }}_latest

      - name: Create git tag for fix release and push
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag release-${{ github.event.inputs.version }}_fix1
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} --tags
