name: Fix Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to fix (e.g., 9)'
        required: true

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  fix-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Apply fix
        run: |
          echo "🔧 Здесь можно внести правки в код, если нужно"
          # Пример: sed -i 's/OldName/NewName/g' src/client/pages/About.tsx

      - name: Build fixed version
        run: npm run build

      - name: Login to Yandex Container Registry
        run: echo "${{ secrets.YC_DOCKER_AUTH }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Build and push Docker image
        run: |
          VERSION=${{ github.event.inputs.version }}
          FIX_TAG="release-${VERSION}_fix1"

          docker build -t $REGISTRY:$FIX_TAG .
          docker tag $REGISTRY:$FIX_TAG $REGISTRY:release-${VERSION}_latest

          docker push $REGISTRY:$FIX_TAG
          docker push $REGISTRY:release-${VERSION}_latest

      - name: Tag and push fix tag
        run: |
          VERSION=${{ github.event.inputs.version }}
          FIX_TAG="release-${VERSION}_fix1"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $FIX_TAG
          git push origin --tags

      - name: Comment to GitHub issue
        run: |
          VERSION=${{ github.event.inputs.version }}
          FIX_TAG="release-${VERSION}_fix1"
          ISSUE_NUMBER=$(gh issue list --search "Release ${VERSION}" --limit 1 --json number --jq '.[0].number')
          COMMENT="✅ Fix for release ${VERSION}: Docker image uploaded as \`${REGISTRY}:${FIX_TAG}\`"
          echo "$COMMENT" | gh issue comment "$ISSUE_NUMBER" --body -
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
